
services:
  db:
    image: postgres:14
    container_name: learning_pg
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: ./backend
    container_name: learning_django
    command: >
      sh -c "until nc -z db 5432;
        do echo '⏳ Waiting for Postgres...'; sleep 1; done;
        echo '✅ Postgres is ready';
        python manage.py makemigrations tracker &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    container_name: learning_frontend
    ports:
      - "3000:3000"
    working_dir: /app
    command: npm run start
    depends_on:
      - web
    environment:
      NODE_ENV: production

volumes:
  pgdata:
